var fs = require("fs");
var promisify = require("./_promisify.js");
Object.defineProperties(module.exports, {
  FileReadStream: { enumerable: true, value: fs.FileReadStream },
  FileWriteStream: { enumerable: true, value: fs.FileWriteStream },
  ReadStream: { enumerable: true, value: fs.ReadStream },
  Stats: { enumerable: true, value: fs.Stats },
  SyncWriteStream: { enumerable: true, value: fs.SyncWriteStream },
  WriteStream: { enumerable: true, value: fs.WriteStream },
  //_toUnixTimestamp: // skipping
  appendFile: { enumerable: true, value: promisify(fs, fs.appendFile, 2) },
  appendFileSync: { enumerable: true, value: fs.appendFileSync.bind(fs) },
  chmod: { enumerable: true, value: promisify(fs, fs.chmod, 2) },
  chmodSync: { enumerable: true, value: fs.chmodSync.bind(fs) },
  chown: { enumerable: true, value: promisify(fs, fs.chown, 3) },
  chownSync: { enumerable: true, value: fs.chownSync.bind(fs) },
  close: { enumerable: true, value: promisify(fs, fs.close, 1) },
  closeSync: { enumerable: true, value: fs.closeSync.bind(fs) },
  createReadStream: { enumerable: true, value: fs.createReadStream.bind(fs) },
  createWriteStream: { enumerable: true, value: fs.createWriteStream.bind(fs) },
  exists: { enumerable: true, value: promisify(fs, fs.exists, 1) },
  existsSync: { enumerable: true, value: fs.existsSync.bind(fs) },
  fchmod: { enumerable: true, value: promisify(fs, fs.fchmod, 2) },
  fchmodSync: { enumerable: true, value: fs.fchmodSync.bind(fs) },
  fchown: { enumerable: true, value: promisify(fs, fs.fchown, 3) },
  fchownSync: { enumerable: true, value: fs.fchownSync.bind(fs) },
  fdatasync: { enumerable: true, value: promisify(fs, fs.fdatasync, 1) },
  fdatasyncSync: { enumerable: true, value: fs.fdatasyncSync.bind(fs) },
  fstat: { enumerable: true, value: promisify(fs, fs.fstat, 1) },
  fstatSync: { enumerable: true, value: fs.fstatSync.bind(fs) },
  fsync: { enumerable: true, value: promisify(fs, fs.fsync, 1) },
  fsyncSync: { enumerable: true, value: fs.fsyncSync.bind(fs) },
  ftruncate: { enumerable: true, value: promisify(fs, fs.ftruncate, 2) },
  ftruncateSync: { enumerable: true, value: fs.ftruncateSync.bind(fs) },
  futimes: { enumerable: true, value: promisify(fs, fs.futimes, 3) },
  futimesSync: { enumerable: true, value: fs.futimesSync.bind(fs) },
  link: { enumerable: true, value: promisify(fs, fs.link, 2) },
  linkSync: { enumerable: true, value: fs.linkSync.bind(fs) },
  lstat: { enumerable: true, value: promisify(fs, fs.lstat, 1) },
  lstatSync: { enumerable: true, value: fs.lstatSync.bind(fs) },
  mkdir: { enumerable: true, value: promisify(fs, fs.mkdir, 1) },
  mkdirSync: { enumerable: true, value: fs.mkdirSync.bind(fs) },
  open: { enumerable: true, value: promisify(fs, fs.open, 2) },
  openSync: { enumerable: true, value: fs.openSync.bind(fs) },
  read: { enumerable: true, value: promisify(fs, fs.read, 5) },
  readFile: { enumerable: true, value: promisify(fs, fs.readFile, 1) },
  readFileSync: { enumerable: true, value: fs.readFileSync.bind(fs) },
  readSync: { enumerable: true, value: fs.readSync.bind(fs) },
  readdir: { enumerable: true, value: promisify(fs, fs.readdir, 1) },
  readdirSync: { enumerable: true, value: fs.readdirSync.bind(fs) },
  readlink: { enumerable: true, value: promisify(fs, fs.readlink, 1) },
  readlinkSync: { enumerable: true, value: fs.readlinkSync.bind(fs) },
  realpath: { enumerable: true, value: promisify(fs, fs.realpath, 1) },
  realpathSync: { enumerable: true, value: fs.realpathSync.bind(fs) },
  rename: { enumerable: true, value: promisify(fs, fs.rename, 2) },
  renameSync: { enumerable: true, value: fs.renameSync.bind(fs) },
  rmdir: { enumerable: true, value: promisify(fs, fs.rmdir, 1) },
  rmdirSync: { enumerable: true, value: fs.rmdirSync.bind(fs) },
  stat: { enumerable: true, value: promisify(fs, fs.stat, 1) },
  statSync: { enumerable: true, value: fs.statSync.bind(fs) },
  symlink: { enumerable: true, value: promisify(fs, fs.symlink, 2) },
  symlinkSync: { enumerable: true, value: fs.symlinkSync.bind(fs) },
  truncate: { enumerable: true, value: promisify(fs, fs.truncate, 2) },
  truncateSync: { enumerable: true, value: fs.truncateSync.bind(fs) },
  unlink: { enumerable: true, value: promisify(fs, fs.unlink, 1) },
  unlinkSync: { enumerable: true, value: fs.unlinkSync.bind(fs) },
  unwatchFile: { enumerable: true, value: fs.unwatchFile.bind(fs) },
  utimes: { enumerable: true, value: promisify(fs, fs.utimes, 3) },
  utimesSync: { enumerable: true, value: fs.utimesSync.bind(fs) },
  watch: { enumerable: true, value: fs.watch.bind(fs) },
  watchFile: { enumerable: true, value: fs.watchFile.bind(fs) },
  write: { enumerable: true, value: promisify(fs, fs.write, 5) },
  writeFile: { enumerable: true, value: promisify(fs, fs.writeFile, 2) },
  writeFileSync: { enumerable: true, value: fs.writeFileSync.bind(fs) },
  writeSync: { enumerable: true, value: fs.writeSync.bind(fs) },
});